version: "3"
services:

  mongodb:
    image: mongo
    ports:
    - "27017:27017"
    logging:
      options:
        max-size: "50m"
        max-file: "2"
    volumes:
    - data-volume:/data/db
    networks:
      - local-redistribution-network

volumes:
  data-volume:

networks:
  local-redistribution-network:
    driver: bridge
